const categories = [
    "Berufe",
    "Hauptstädte",
    "Länder",
    "Gemüsesorten",
    "Musiker",
    "Gerichte",
    "Pastasorten",
    "Getränke",
    "Oscar ausgezeichnete Filme",
    "Luxusmarken",
    "Musikinstrumente",
    "Flüsse",
    "Insekten",
    "Sportarten",
    "Gewürze",
    "Alkoholische Getränke",
    "Automarken",
    "Games",
    "Phobien",
    "Hunderassen",
    "Planeten und Sterne",
    "Psychologische Fachbegriffe",
    "Chemische Elemente",
    "Feiertage",
    "Parfummarken",
    "Disney-Filme",
    "Städte in Deutschland",
    "Eissorten",
    "Automarken",
    "Lebensmittelmarken",



    "Synonyme für den S** Erguss",
    "S**-Stellungen"
]